Odoo tutorials - Getting started
Gilmaciasr/real_state pull request #1
Opened 2023-04-19 00:33 UTC by Gilmaciasr

Start of the getting started section:
Chapter 1 - reading about modules structure.
Chapter 2 - Setting up git and repositories, run odoo for the first time and set up the instance.
Chapter 3 - Create first directories with init and manifest files.
Chapter 4 - estate_property model creation and attributes definitions.
Chapter 5 -  Defining access rights and security folder. Add file to the data field in manifest.

2023-04-19 20:05 UTC, Gilmaciasr commented
@JesusValdez96

2023-04-19 22:08 UTC, JesusValdez96 commented
@Gilmaciasr Please on the PR description add the link to the lessons. The same applies to the first commit.

2023-04-19 23:33 UTC, JesusValdez96 requested changes

2023-04-20 03:16 UTC, JesusValdez96 requested changes
Change the PR Title according to the guidelines: [TAG] module: Change message T#00000

2023-04-20 16:25 UTC, JesusValdez96 commented on estate/models/estate_property.py
> +    selling_price = fields.Float(readonly=True, copy=False)
@Gilmaciasr if you decide to keep this, add the chapter and exercise to the PR description

2023-04-20 23:46 UTC, Gilmaciasr commented on estate/models/estate_property.py
> +    selling_price = fields.Float(readonly=True, copy=False)
@JesusValdez96  it's from another lesson, i'm going to change it

2023-04-20 23:50 UTC, JesusValdez96 requested changes

2023-04-20 23:50 UTC, JesusValdez96 commented on estate/models/estate_property.py
> +        string='Orientation',
Same in other cases.

```suggestion
        string="Orientation",
```

2023-04-21 00:06 UTC, JesusValdez96 requested changes

2023-04-21 00:19 UTC, Gilmaciasr commented
@JesusValdez96  Can you please review this again? thx

2023-04-21 00:36 UTC, merged