[ADD] estate: Reports to properties and salesman creation T#70778
Gilmaciasr/real_state pull request #13
Opened 2023-05-22 16:57 UTC by Gilmaciasr

In this update now you can create reports for any property that includes its offers, if the property is already set to sold a message about the invoice is included too. Salesman's report shows all the properties that belongs to a salesman and its offers.
Link to the lesson:
https://www.odoo.com/documentation/16.0/developer/tutorials/pdf_reports.html
![image](https://github.com/Gilmaciasr/real_state/assets/114004225/988e117e-3306-4367-bb8a-e5b638fb3009)
![image](https://github.com/Gilmaciasr/real_state/assets/114004225/2d6d4026-b33a-42f7-af95-61fb82c22e2b)
![image](https://github.com/Gilmaciasr/real_state/assets/114004225/ed043d62-bf8d-4b58-a494-92c3bdc43674)
![image](https://github.com/Gilmaciasr/real_state/assets/114004225/b16f1ebf-500e-4b99-9523-98c7f9bfe6ef)
![image](https://github.com/Gilmaciasr/real_state/assets/114004225/f6481185-dd76-468b-9813-89f9281fde7f)

2023-05-22 16:59 UTC, Gilmaciasr commented
@JesusValdez96

2023-05-22 18:39 UTC, JesusValdez96 commented
@Gilmaciasr Drop first two commits with git rebase because they're duplicated

2023-05-23 04:45 UTC, JesusValdez96 requested changes

2023-05-23 13:50 UTC, Gilmaciasr commented
@JesusValdez96  Done!

2023-05-24 17:07 UTC, merged