[ADD] estate: Add new features to offer, area and best price fields T#70778
Gilmaciasr/real_state pull request #3
Opened 2023-04-27 16:00 UTC by Gilmaciasr

This PR contains changes made according to chapter 9 from odoo getting started.
Link to the lesson:
https://www.odoo.com/documentation/15.0/developer/tutorials/getting_started/09_compute_onchange.html
Video of the changes:
https://youtu.be/iP9t6-fuJ2M
https://youtu.be/LUs6vxDewbs

2023-04-28 02:24 UTC, JesusValdez96 requested changes

2023-04-28 02:24 UTC, JesusValdez96 commented on estate/views/estate_property_views.xml
> +                <field name="offer_ids" string="Offer">
I think that odoo converts that automatically

2023-04-28 02:24 UTC, JesusValdez96 commented on estate/views/estate_property_views.xml
> +              <page string="Other_info">
Why the "_"???

```suggestion
              <page string="Other info">
```

2023-04-28 18:38 UTC, Gilmaciasr commented on estate/models/estate_property_offer.py
>          comodel_name='estate.property',
Done.
I also changed some string above that has the same issue.

2023-04-28 18:39 UTC, Gilmaciasr commented on estate/models/estate_property_offer.py
> +            )
Okay!

2023-04-28 18:39 UTC, Gilmaciasr commented on estate/models/estate_property_offer.py
> +            )
Roger that!

2023-04-28 18:43 UTC, Gilmaciasr commented on estate/views/estate_property_views.xml
> +            <field name="living_area" string="Living_Area_(sqm)"/>
in previous PR you suggest something like that, maybe i got confused.

2023-04-29 20:48 UTC, JesusValdez96 requested changes
Hi @Gilmaciasr Good job! only two comments.

2023-04-29 20:48 UTC, JesusValdez96 commented on estate/models/estate_property_offer.py
> +    create_date = fields.Date(default=fields.Date.today())
The date of fields.Date.today() will always be equal to the date the server was started if you don't use a lambda function.

```suggestion
    create_date = fields.Date(default=lambda self: fields.Date.today())
```

2023-05-02 16:06 UTC, merged