[ADD] estate: Accept and refuse offer functions T#70778
Gilmaciasr/real_state pull request #4
Opened 2023-05-02 17:03 UTC by Gilmaciasr

In this one i added buttons to change property status with restriction, if a property is sold it cannot change to canceled and viceversa, buttons to accept or refuse an offer were added on offer tab, when accept an offer the selling price and buyer are set  automatically a property cannot have 2 offers accepted.
Link to the lesson:
https://www.odoo.com/documentation/15.0/developer/tutorials/getting_started/10_actions.html
Video showing changes:
https://youtu.be/wAEVm_NHtNs

2023-05-02 17:38 UTC, Gilmaciasr commented
@JesusValdez96  PR #4 is ready.

2023-05-03 00:11 UTC, JesusValdez96 requested changes
@Gilmaciasr Good job, any questions do not hesitate to ask me.

2023-05-03 00:11 UTC, JesusValdez96 commented on estate/views/estate_property_views.xml
> +            <button name= "cancel_button_action" type="object" string="Cancel"/>
```suggestion
            <button name="sold_button_action" type="object" string="Sold"/>
            <button name="cancel_button_action" type="object" string="Cancel"/>
```

2023-05-03 00:11 UTC, JesusValdez96 commented on estate/views/estate_property_offer_views.xml
> +        <button name="refuse_offer_button_action" string="Refuse" type="object" icon="fa-check"/>
where can I see this? there's no property offers tree view or property offers menu item in the web page, this two views are necessary?

2023-05-03 01:44 UTC, Gilmaciasr commented on estate/models/estate_property_offer.py
> +            record.status = "refused"
@JesusValdez96 
In the instructions of the exercise they mention that this is a good practice.
https://www.odoo.com/documentation/15.0/developer/tutorials/getting_started/10_actions.html
![image](https://user-images.githubusercontent.com/114004225/235818947-6ad589cb-af53-444e-b173-0a59ce58c93f.png)

2023-05-03 02:29 UTC, merged