[ADD] estate: Apply constraints to selling price and other fields T#70778
Gilmaciasr/real_state pull request #5
Opened 2023-05-03 13:43 UTC by Gilmaciasr

Add SQL constraints to Tag and Type to avoid duplicate names, for selling_price, expected_price and offers constraints were applied to avoid assigning a negative value, the same was established for living area and garden area to avoid a total_area result of 0 or negative values.
Create a constraint to accept an offer only if its price is at least 90% of the expected price, for that the accept_offer_button_action
had to be changed in order to trigger the selling price update and therefore apply the constraint.
Link to the lesson:
https://www.odoo.com/documentation/15.0/developer/tutorials/getting_started/11_constraints.html
Video of current changes:
https://youtu.be/NuDJWH2toOA

2023-05-03 13:44 UTC, Gilmaciasr commented
@JesusValdez96  Ready PR#5! Can you please check it out?

2023-05-04 00:03 UTC, JesusValdez96 requested changes

2023-05-04 00:03 UTC, JesusValdez96 commented on estate/models/estate_property_offer.py
> +            self.property_id.buyer_id = None
```suggestion
            record.property_id.selling_price = 0
            record.property_id.buyer_id = False
```

2023-05-04 00:03 UTC, JesusValdez96 commented on estate/models/estate_property_offer.py
> +                self.property_id.buyer_id = record.partner_id
```suggestion
                record.property_id.selling_price = record.price
                record.property_id.buyer_id = record.partner_id
```

2023-05-04 15:18 UTC, Gilmaciasr commented
@JesusValdez96  suggested changes done!

2023-05-04 16:45 UTC, merged