[ADD] estate: new features on UI in all models T#70778
Gilmaciasr/real_state pull request #6
Opened 2023-05-04 17:44 UTC by Gilmaciasr

This update include several new features all applied to the user interface, such as tags with colors on the property tree view, colors to identify if a property has been sold or if it has any offer, in the property form now the offers show in color if it was accepted or refused and when the status changes the buttons dissapear, with that once a change has been made it cannot be modified by the same record. Also a stat button was added to the property type form view to link a particular type to its related offer.
All changes were made to make the interface more intuitive and good looking to the user.
All details for this lesson can be found here:
https://www.odoo.com/documentation/15.0/developer/tutorials/getting_started/12_sprinkles.html
You can checkout the changes watching the following videos:
https://youtu.be/Ak9WKwACerM
https://youtu.be/Twe1Cgd7xFA
https://youtu.be/QCRh8iMOEIg
https://youtu.be/kNdQsCD9Epo
https://youtu.be/jPPOGwLNXxo
https://youtu.be/-BJyIpPGeps
https://youtu.be/fC6yuN57K0w

2023-05-04 17:45 UTC, Gilmaciasr commented
@JesusValdez96  PR6 is ready Master!

2023-05-05 05:13 UTC, JesusValdez96 requested changes

2023-05-05 05:15 UTC, JesusValdez96 commented
@Gilmaciasr Good job! only two comments and change the link to the lesson in the pr description, you are using 15.0 documentation.

2023-05-05 13:43 UTC, Gilmaciasr commented
@JesusValdez96 Update ready!

2023-05-05 16:46 UTC, merged