[ADD] estate: modify user model view and behavior on properties and offer creation/deletion T#70778
Gilmaciasr/real_state pull request #7
Opened 2023-05-09 14:52 UTC by Gilmaciasr

In this update the following has been applied:
-Inherited user view to show just few fields and add a tab to real estate properties, now you can see which properties are being sold by each salesman(user) directly on user view.
-Apply some methods to prevent deletion of properties, just new or canceled can be deleted. A user error is prompt if so.
-On offer creation a restriction has been applied, new offers should be higher than the previous one in order to be saved.
Link to the lesson:
https://www.odoo.com/documentation/16.0/developer/tutorials/getting_started/13_inheritance.html
Links to the videos:
https://youtu.be/RimhVknYQ0w
https://youtu.be/2quJ-C075to

2023-05-09 14:52 UTC, Gilmaciasr commented
@JesusValdez96 ready for the show!

2023-05-12 04:31 UTC, JesusValdez96 requested changes

2023-05-12 04:31 UTC, JesusValdez96 commented on estate/models/estate_property.py
> +            return True
```suggestion
        for record in self:
            prices = record.mapped("offer_ids.price")
            if prices and new_offer_price < max(prices):
                raise exceptions.UserError(_("The new offer should be higher than %s", max(prices)))
        return True
```

2023-05-12 04:31 UTC, JesusValdez96 commented on estate/views/res_users_views.xml
> +      <xpath expr="//form" position="replace">
don't use position="replace" if not necessary

2023-05-12 04:31 UTC, JesusValdez96 commented on estate/views/res_users_views.xml
> +      <xpath expr="//form" position="replace">
why did you overwrite the whole form? it's better only add the new page to the notebook section with a specific expr to preferences page and position="after"

2023-05-12 18:47 UTC, Gilmaciasr commented on estate/views/res_users_views.xml
> +      <xpath expr="//form" position="replace">
@JesusValdez96 I misunderstood the instructions, i noticed on later exercises and there i changed it, but i'll fix it at this review right away,

2023-05-12 23:16 UTC, merged